-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (CreateBlogpostV2RequiredArguments, RecordAnalyticsRequiredArguments, apiVersion, createBlogpostV2, recordAnalytics)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


apiVersion : SelectionSet String RootMutation
apiVersion =
    Object.selectionForField "String" "apiVersion" [] Decode.string


type alias RecordAnalyticsRequiredArguments =
    { events : List Api.InputObject.NovaEvent }


recordAnalytics :
    RecordAnalyticsRequiredArguments
    -> SelectionSet String RootMutation
recordAnalytics requiredArgs____ =
    Object.selectionForField "String" "recordAnalytics" [ Argument.required "events" requiredArgs____.events (Api.InputObject.encodeNovaEvent |> Encode.list) ] Decode.string


type alias CreateBlogpostV2RequiredArguments =
    { date : Float
    , title : String
    , content : String
    }


createBlogpostV2 :
    CreateBlogpostV2RequiredArguments
    -> SelectionSet decodesTo Api.Object.Post
    -> SelectionSet decodesTo RootMutation
createBlogpostV2 requiredArgs____ object____ =
    Object.selectionForCompositeField "createBlogpostV2" [ Argument.required "date" requiredArgs____.date Encode.float, Argument.required "title" requiredArgs____.title Encode.string, Argument.required "content" requiredArgs____.content Encode.string ] object____ identity
